# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "libcore"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/sagernet/gomobile"
      - dependency-name: "github.com/sagernet/sing-box"
      - dependency-name: "github.com/xchacha20-poly1305/*"